version: '3.8'

services:
  web:
    container_name: python_research_tool
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: python_research_tool_postgres
    image: postgres:14.2
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
