# Generated by Django 4.0.4 on 2022-07-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_number', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type_title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'data_type',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'mode',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskDataSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_size_title', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=128)),
                ('data_size_numeric', models.PositiveIntegerField()),
                ('comment', models.TextField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.task')),
            ],
            options={
                'db_table': 'task_data_size',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurable_start_time', models.DateTimeField(auto_now=True)),
                ('measurable_end_time', models.DateTimeField(auto_now=True)),
                ('duration_nano_sec', models.PositiveBigIntegerField(null=True)),
                ('space_taken_bytes', models.PositiveBigIntegerField(null=True)),
                ('cpu_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.cpu')),
                ('data_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.datatype')),
                ('mode_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.mode')),
                ('task_data_size_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.taskdatasize')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task_logs.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
