# Generated by Django 4.0.4 on 2022-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='measurable_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='measurable_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
